### ISSUE TITLE
Audit and remove Storybook-specific violations

### ISSUE THREAD

**Issue by jojolee1996** [user-interviews/ui-design-system#96]
Examples:
![image](https://user-images.githubusercontent.com/70974778/101089557-2c3e0680-356a-11eb-9149-3b981adbd859.png)
![image (1)](https://user-images.githubusercontent.com/70974778/101089552-2b0cd980-356a-11eb-9d7f-90281925dd00.png)

**Comment by fausgaitan** [comment]
Hey @jojolee1996 
Once again sorry I just took this task from you just like that, for some reason I was sure @wenzeng4  assigned it to me since I've worked on the input fields in the past! 😅

This seems like a broad ticket, but if you want to audit any other component feel free to add them [here](https://www.notion.so/userinterviews1/DS-Violations-b4c3c12921ea49d7a4aa775cd609b83c)

**Comment by jojolee1996** [comment]
@fausgaitan No prob! It makes sense for you to take it :)
